// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6-nYhdQTF8BAeElbilfvDAALRDnjSzsQ',
    appId: '1:1095194517488:web:a4dc67f1e3e86289964735',
    messagingSenderId: '1095194517488',
    projectId: 'authtuto-6b64f',
    authDomain: 'authtuto-6b64f.firebaseapp.com',
    storageBucket: 'authtuto-6b64f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGvTQTO8kprEG4Lr4GHvxrQVW_QUzlK-Q',
    appId: '1:1095194517488:ios:fb36363e2ec8f750964735',
    messagingSenderId: '1095194517488',
    projectId: 'authtuto-6b64f',
    storageBucket: 'authtuto-6b64f.appspot.com',
    iosBundleId: 'com.example.googleSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGvTQTO8kprEG4Lr4GHvxrQVW_QUzlK-Q',
    appId: '1:1095194517488:ios:fb36363e2ec8f750964735',
    messagingSenderId: '1095194517488',
    projectId: 'authtuto-6b64f',
    storageBucket: 'authtuto-6b64f.appspot.com',
    iosBundleId: 'com.example.googleSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6-nYhdQTF8BAeElbilfvDAALRDnjSzsQ',
    appId: '1:1095194517488:web:ff10d058c1cf6336964735',
    messagingSenderId: '1095194517488',
    projectId: 'authtuto-6b64f',
    authDomain: 'authtuto-6b64f.firebaseapp.com',
    storageBucket: 'authtuto-6b64f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzu5oYrqfV6uiw0MoosNnwFcO2-h5gYhM',
    appId: '1:1095194517488:android:c890efafe9ed666b964735',
    messagingSenderId: '1095194517488',
    projectId: 'authtuto-6b64f',
    storageBucket: 'authtuto-6b64f.appspot.com',
  );

}